### ISSUE TITLE
Despliegue de proyectos a través de interfaz web

### ISSUE THREAD

**Issue by borillo** [universitatjaumei/ship#1]
Inicialmente, contar únicamente con un input donde establecemos la key del proyecto.
Esta key está detallada en el fichero de configuración YAML.
Tendremos un botón de DEPLOY que llamará al servicio REST y este al API de SHIP.

**Comment by vrubert** [comment]
Funcionando todo a partir de este commit:

https://github.com/universitatjaumei/ship/commit/9e1fc465507dbb3255f46e07b82e8a3e0180ca9c
